name: deployment
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 1440

    steps:

    - name: Import File
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/winrar.exe -OutFile winrar.exe
    - name: Configuring
      run: |
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy ngrok.exe C:\Windows\ngrok.exe
        
    - name: Deploying
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
        cmd /c start.bat
        
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 1
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 2
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 3
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 4
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 5
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 6
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
      
    - name: Looping Process 7
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2I55cjy6KzjkPA6nrl0pyEGvEna_pQTqNjemjvXp7xWDCg2s
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
      
    - name: Host
      run: |
        cmd /c loop.bat
